version: "3"
services: 
  web:
    build: ./app/
    ports: 
      - 8080:8080
      - 8443:8443
    volumes: 
      - ./:/works/streamini
    command: "/works/code-server --allow-http --no-auth /works/streamini"


